language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
          compiler: gcc
          env: SOURCES=ubuntu-toolchain-r-test
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++
                - gfortran
                - libblas-dev
                - liblapack-dev
                - libatlas-base-dev
                - libopenblas-base
                - libopenblas-dev
                - openmpi-bin
                - libopenmpi-dev
                - libpython2.7
                - libboost-all-dev
        - os: linux
          sudo: required
          python: 3.4
          compiler: gcc
          env: SOURCES=ubuntu-toolchain-r-test
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++
                - gfortran
                - libblas-dev
                - liblapack-dev
                - libatlas-base-dev
                - libopenblas-base
                - libopenblas-dev
                - openmpi-bin
                - libopenmpi-dev
                - libpython2.7
                - libboost-all-dev
        - os: linux
          sudo: required
          python: 3.5
          compiler: gcc
          env: SOURCES=ubuntu-toolchain-r-test
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++
                - gfortran
                - libblas-dev
                - liblapack-dev
                - libatlas-base-dev
                - libopenblas-base
                - libopenblas-dev
                - openmpi-bin
                - libopenmpi-dev
                - libpython2.7
                - libboost-all-dev
        - os: linux
          sudo: required
          python: 3.6
          compiler: gcc
          env: SOURCES=ubuntu-toolchain-r-test
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++
                - gfortran
                - libblas-dev
                - liblapack-dev
                - libatlas-base-dev
                - libopenblas-base
                - libopenblas-dev
                - openmpi-bin
                - libopenmpi-dev
                - libpython2.7
                - libboost-all-dev

        - os: osx
          language: generic
          env: PYTHON=2.7
        - os: osx
          language: generic
          env: PYTHON=3.4.4
        - os: osx
          language: generic
          env: PYTHON=3.5.4
        - os: osx
          language: generic
          env: PYTHON=3.6.4

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi

install:
   - python -m pip install --upgrade pip
   - python -m easy_install -U setuptools
   - python -m pip install numpy
   - python -m pip install pytest 
   - python -m pip install cvxpy scs ecos 
   - python -m pip --no-cache-dir install --index-url https://test.pypi.org/simple scola

# command to run tests
script:
  - python -m pytest ./tests
